server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserServices
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true