server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RatingServices
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: RATING_SERVICE

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka